---
- hosts: all
  become: yes
  roles:
    - { role: geerlingguy.ruby,
        ruby_install_from_source: true,
        ruby_download_url: http://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.6.tar.gz,
        ruby_version: 2.7.6,
        ruby_install_bundler: true
    }
  tasks:
    - name: Install gems using a Gemfile in another directory
      community.general.bundler:
        state: present
        gemfile: /vagrant/Gemfile

    - name: Install build tools via apt
      ansible.builtin.apt:
        pkg:
          - build-essential
          - git
          - python3-pip
          - jekyll
          - sshfs
          - libcurl4-openssl-dev
          - libxml2-dev
        state: present

    - name: Install github-pages gem
      community.general.gem:
        name: github-pages
        state: present

    - name: Install kramdown gem
      community.general.gem:
        name: kramdown
        state: present

    - name: Install kramdown-parser-gfm gem
      community.general.gem:
        name: kramdown-parser-gfm
        state: present

    - name: Install build tools via pip
      ansible.builtin.pip:
        name:
          - setuptools
          - wheel
          - pyyaml==5.3.1
          - requests
          - beautifulsoup4
          - GitPython
          - git_root
          - pandas
          - html5lib
          - python-dateutil
          - lxml
          - favicons

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
