---
- hosts: all
  become: yes
  tasks:
    - name: Install build tools via apt
      apt:
        pkg:
          - build-essential
          - git
          - ruby2.7.1
        state: present
    - name: Install build tools via gem
      community.general.gem:
        name:
          - github-pages
          - bundler
          - kramdown
          - kramdown-parser-gfm
        state: present
    - name: Install build tools via pip
      ansible.builtin.pip:
        name:
          - setuptools
          - wheel
          - pyyaml==5.3.1
          - requests
          - beautifulsoup4
          - git_root
          - pandas
          - html5lib
          - python-dateutil
          - lxml
          - favicons
    - name: Install R build requirements
      ansible.builtin.command: |
        Rscript renv/activate.R
        Rscript -e 'renv::restore()'