---
- hosts: all
  become: yes
  roles:
    - { role: geerlingguy.ruby,
        ruby_install_from_source: true,
        ruby_download_url: http://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.6.tar.gz,
        ruby_version: 2.7.6,
        ruby_install_bundler: true
    }
  tasks:
    - name: Install build tools via apt
      ansible.builtin.apt:
        pkg:
          - build-essential
          - git
          - python3-pip
          - r-base
          - jekyll
          - sshfs
        state: present

    - name: Install github-pages gem
      community.general.gem:
        name: github-pages
        state: present

    - name: Install kramdown gem
      community.general.gem:
        name: kramdown
        state: present

    - name: Install kramdown-parser-gfm gem
      community.general.gem:
        name: kramdown-parser-gfm
        state: present

    - name: Install build tools via pip
      ansible.builtin.pip:
        name:
          - setuptools
          - wheel
          - pyyaml==5.3.1
          - requests
          - beautifulsoup4
          - GitPython
          - git_root
          - pandas
          - html5lib
          - python-dateutil
          - lxml
          - favicons

    - name: Install R build requirements
      ansible.builtin.apt:
        pkg:
          - r-cran-knitr
          - r-cran-shiny
          - r-cran-tidyverse
        state: present

#    - name: Synchronization using rsync protocol (pull)
#      ansible.posix.synchronize:
#        mode: pull
#        src: 10.0.2.2/{{}}/_episodes
#        dest: /Materials/{{}}/_episodes

# This is the 'R' way to do things and takes 30+ mins
#    - name: Install R build requirements
#      ansible.builtin.command: /usr/bin/Rscript -e "{{item}}"
#      with_items:
#        - install.packages('renv')
#        - renv::restore()