---
- hosts: all
  become: yes
  tasks:
    - name: Install build tools via apt
      ansible.builtin.apt:
        pkg:
          - build-essential
          - git
          - ruby
          - ruby-dev
          - python3-pip
          - r-base
        state: present

    - name: Install github-pages gem
      gem:
        name: github-pages
        state: present

    - name: Install bundler gem
      gem:
        name: bundler
        state: present

    - name: Install kramdown gem
      gem:
        name: kramdown
        state: present

    - name: Install kramdown-parser-gfm gem
      gem:
        name: kramdown-parser-gfm
        state: present

    - name: Install build tools via pip
      ansible.builtin.pip:
        name:
          - setuptools
          - wheel
          - pyyaml==5.3.1
          - requests
          - beautifulsoup4
          - git_root
          - pandas
          - html5lib
          - python-dateutil
          - lxml
          - favicons

    - name: Install R build requirements
      ansible.builtin.apt:
        pkg:
          - r-cran-knitr
          - r-cran-shiny
          - r-cran-tidyverse
        state: present

# This is the 'R' way to do things and takes 30+ mins
#    - name: Install R build requirements
#      ansible.builtin.command: /usr/bin/Rscript -e "{{item}}"
#      with_items:
#        - install.packages('renv')
#        - renv::restore()