Vagrant.configure("2") do |config|

    config.vm.provider :vmware_fusion do |v|
        v.memory = 1024
        v.cpus = 2
        v.gui = true              # headless may or may not work
        v.linked_clone = false    # this fixes an obtuse vmrun error
        v.ssh_info_public = true  # next two lines fix a networking bug
        v.vmx["ethernet0.virtualdev"] = "vmxnet3"
    end

    # Set the box type
    config.vm.box = "starboard/ubuntu-arm64-20.04.5"
    config.vm.box_version = "20221120.20.40.0"
    # Set the box Name
    config.vm.define "LessonBox"

    # Use :ansible to provision
    config.vm.provision :ansible_local do |ansible|
        ansible.install_mode = "pip3"
        ansible.version = "latest"
        ansible.become = true
        ansible.playbook = "provision.yml"
        ansible.galaxy_role_file = "requirements.yml"
        ansible.galaxy_roles_path = "/etc/ansible/roles"
        ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
    end

    config.vm.network "forwarded_port", guest: 8124, host: 8124
    config.vm.network "forwarded_port", guest: 8125, host: 8125

    config.ssh.forward_agent = true
end
